In [1]:
# pip install numpy 
import numpy as np


In [3]:
l = [1, 2, 3]

numpy_array = np.array(l)

In [4]:
numpy_array

array([1, 2, 3])

In [27]:
numpy_array1 = np.ones((5, 6))

In [16]:
numpy_array.nbytes

12

In [18]:
numpy_array[0] = 10

In [19]:
numpy_array

array([10,  2,  3])

In [23]:
numpy_array[0] = False

In [24]:
numpy_array

array([0, 2, 3])

In [29]:
numpy_array1[0][5] = 7
numpy_array1

array([[1., 1., 1., 1., 1., 7.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [35]:
np.array(['wdwdwda', 'aab', 'cddwddw'])

array(['wdwdwda', 'aab', 'cddwddw'], dtype='<U7')

In [30]:
numpy_array1[1,4] = 5
numpy_array1

array([[1., 1., 1., 1., 1., 7.],
       [1., 1., 1., 1., 5., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [40]:
numpy_array1[1:3]

array([[1., 1., 1., 1., 5., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [60]:
f = numpy_array1[1:3, :3].copy()

In [61]:
f  + 1 

array([[5., 5., 5.],
       [5., 5., 5.]])

In [64]:
numpy_array

array([0, 2, 3])

In [66]:
numpy_array + 1

array([1, 3, 4])

In [67]:
numpy_array * 10 

array([ 0, 20, 30])

In [68]:
numpy_array % 2

array([0, 0, 1], dtype=int32)

In [69]:
np.sin(numpy_array)

array([0.        , 0.90929743, 0.14112001])

In [73]:
numpy_array / numpy_array

C:\Users\i.betlei\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.])

In [74]:
np.cos(0)

1.0

In [75]:
numpy_array * 10 

array([ 0, 20, 30])

In [76]:
l = [1, 2, 3, -3, -5, 11, 15, -7, -6]

numpy_array = np.array(l)

In [77]:
numpy_array

array([ 1,  2,  3, -3, -5, 11, 15, -7, -6])

In [83]:
numpy_array[(numpy_array > 0) & (numpy_array % 2 == 0)] = 10

In [84]:
numpy_array

array([ 1, 10,  3, -3, -5, 11, 15, -7, -6])

In [90]:
numpy_array[(numpy_array > 0) & (numpy_array % 2 == 0)]

In [86]:
f

array([10])

In [87]:
f[0] = 1

In [88]:
numpy_array

array([ 1, 10,  3, -3, -5, 11, 15, -7, -6])

In [2]:
3 * 0.1

0.30000000000000004

In [7]:
import numpy

numpy.inf > numpy.nan

False

In [8]:
numpy.nan - numpy.nan

nan

In [9]:
numpy.nan == numpy.nan

False

In [10]:
numpy.nan in set([numpy.nan])

True

In [13]:
numpy.nan in set([numpy.nan])

True

In [14]:
numpy.isnan(numpy.nan)

True

In [15]:
0 * numpy.nan

nan